FROM intellio-base-dev:latest

# 실행 권한 부여 (볼륨 마운트된 스크립트에 권한 부여)
RUN mkdir -p /tmp/scripts
COPY backend/start-celery-stockeasy.sh /tmp/scripts/
RUN chmod +x /tmp/scripts/start-celery-stockeasy.sh

# Command to run the application
CMD ["sh", "-c", "chmod +x ./start-celery-stockeasy.sh && ./start-celery-stockeasy.sh"] 