services:
  postgres:
    env_file:
      - .env.development
  base-image-dev:
    build:
      context: .
      dockerfile: Dockerfile.base.dev
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: intellio-base-dev:latest
    volumes:
      - ./backend:/backend
    profiles: ["build"]

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi.dev
      args:
        BUILDKIT_INLINE_CACHE: 1
    volumes:
      - ./backend:/backend:rw,delegated
    env_file:
      - .env.development
    environment:
      - ENV=development

  stock-data-collector:
    build:
      context: .
      dockerfile: Dockerfile.stockeasy.collector.dev
      args:
        BUILDKIT_INLINE_CACHE: 1
    volumes:
      - ./backend:/backend:rw,delegated
    env_file:
      - ./backend/.env.development
    environment:
      - ENV=development

  celery-doceasy:
    build:
      context: .
      dockerfile: Dockerfile.celery.doceasy.dev
    volumes:
      - ./backend:/backend
    env_file:
      - .env.development


  celery-stockeasy:
    build:
      context: .
      dockerfile: Dockerfile.celery.stockeasy.dev
    volumes:
      - ./backend:/backend
    env_file:
      - .env.development





