FROM python:3.11.9-slim

WORKDIR /backend

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    libpq-dev \
    python3-dev \
    pkg-config \
    libcairo2-dev \
    libgirepository1.0-dev \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements file
COPY backend/requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir wheel setuptools && \
    if [ "$ENV" = "development" ] ; then \
        echo "Installing with cache for development" && \
        pip install -r requirements.txt ; \
    else \
        echo "Installing without cache for production" && \
        pip install --no-cache-dir -r requirements.txt ; \

# Copy backend code
COPY backend/ .

# Set environment variables
ENV PYTHONPATH=/backend

# Expose port
EXPOSE 8000

RUN chmod +x ./start-fastapi.sh

# Command to run the application
CMD ["./start-fastapi.sh"] 