FROM python:3.11.9-slim

WORKDIR /backend

# 시스템 의존성 설치
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Python 의존성 설치
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 소스코드 복사
COPY backend/ .

# 환경변수 설정
ENV PYTHONPATH=/backend


# Add entrypoint script
RUN chmod +x ./start-celery-doceasy.sh

CMD ["./start-celery-doceasy.sh"] 