
services:
  postgres:
    env_file:
      - .env.production
  base-image-prod:
    build:
      context: .
      dockerfile: Dockerfile.base.prod
    image: intellio-base-prod:latest
    volumes:
      - ./backend:/backend
      #- ./backend/stockeasy/telegram_channels.json:/app/backend/stockeasy/telegram_channels.json
    profiles: ["build"]

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi.prod
    env_file:
      - .env.production
    environment:
      - ENV=production
    volumes:
      - ./backend:/backend
    

  celery-doceasy:
    build:
      context: .
      dockerfile: Dockerfile.celery.doceasy.prod
    env_file:
      - .env.production
    environment:
      - ENV=production
    volumes:
      - ./backend:/backend

  celery-stockeasy:
    build:
      context: .
      dockerfile: Dockerfile.celery.stockeasy.prod
    env_file:
      - .env.production
    environment:
      - ENV=production
    volumes:
      - ./backend:/backend

