services:
  postgres:
    env_file:
      - .env.development
  base-image-dev:
    build:
      context: .
      dockerfile: Dockerfile.base.dev
    image: intellio-base-dev:latest
    volumes:
      - ./backend:/backend
    profiles: ["build"]

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi.dev
    volumes:
      - ./backend:/backend:rw,delegated
    env_file:
      - .env.development
    environment:
      - ENV=development

  celery-doceasy:
    build:
      context: .
      dockerfile: Dockerfile.celery.doceasy.dev
    volumes:
      - ./backend:/backend
    env_file:
      - .env.development


  celery-stockeasy:
    build:
      context: .
      dockerfile: Dockerfile.celery.stockeasy.dev
    volumes:
      - ./backend:/backend
    env_file:
      - .env.development





