version: '3.8'

services:


  fastapi:
    volumes:
      - ./backend:/backend
    env_file:
      - .env.development
      #- backend/.env.development

    environment:
      - ENV=development

  celery-doceasy:
    volumes:
      - ./backend:/backend
    env_file:
      - .env.development
      #- backend/.env.development  


  celery-stockeasy:
    volumes:
      - ./backend:/backend
    env_file:
      - .env.development
      #- backend/.env.development


