version: '3.8'

services:
  # nginx:
  #   ports:
  #     - "8080:80"  # 개발환경은 8080 포트 사용
  #   volumes:
  #     - ./nginx/intellio.dev.conf:/etc/nginx/conf.d/default.conf
  #   environment:
  #     - NODE_ENV=development

  # frontend-doceasy:
  #   environment:
  #     - NODE_ENV=development

  fastapi:
    environment:
      - ENV=development
