version: '3.8'

services:
  postgres:
    image: postgres:15
    command: postgres -c timezone=Asia/Seoul
    env_file:
      - .env
    environment:
      # POSTGRES_DB: ${POSTGRES_DB}
      # POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_MAX_CONNECTIONS: ${POSTGRES_MAX_CONNECTIONS:-100}
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      TZ: Asia/Seoul
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5055:80"
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  tika:
    image: apache/tika:latest
    ports:
      - "9998:9998"
    environment:
      - JAVA_OPTS=-Xmx1g
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9998/tika"]
      interval: 10s
      timeout: 5s
      retries: 3

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"

    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  celery-doceasy:
    build:
      context: .
      dockerfile: Dockerfile.celery.doceasy
    depends_on:
      - redis
      - postgres
    networks:
      - app-network

  celery-stockeasy:
    build:
      context: .
      dockerfile: Dockerfile.celery.stockeasy
    depends_on:
      - redis
      - postgres
    networks:
      - app-network

  flower:
    image: mher/flower
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery-doceasy
      - celery-stockeasy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
