"""초기_TimescaleDB_테이블_생성

Revision ID: 016c2b084c47
Revises: 
Create Date: 2025-06-04 16:41:22.523755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '016c2b084c47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('market_indices', 'time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='시간 (UTC)',
               existing_nullable=False)
    op.alter_column('market_indices', 'index_code',
               existing_type=sa.VARCHAR(length=20),
               comment='지수 코드 (KOSPI, KOSDAQ)',
               existing_nullable=False)
    op.alter_column('market_indices', 'index_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='지수 값',
               existing_nullable=False)
    op.alter_column('market_indices', 'change_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='전일대비 변동',
               existing_nullable=True)
    op.alter_column('market_indices', 'change_rate',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='전일대비 변동률(%)',
               existing_nullable=True)
    op.alter_column('market_indices', 'volume',
               existing_type=sa.BIGINT(),
               comment='거래량',
               existing_nullable=True)
    op.alter_column('market_indices', 'trading_value',
               existing_type=sa.BIGINT(),
               comment='거래대금',
               existing_nullable=True)
    op.alter_column('market_indices', 'rise_count',
               existing_type=sa.INTEGER(),
               comment='상승 종목 수',
               existing_nullable=True)
    op.alter_column('market_indices', 'fall_count',
               existing_type=sa.INTEGER(),
               comment='하락 종목 수',
               existing_nullable=True)
    op.alter_column('market_indices', 'unchanged_count',
               existing_type=sa.INTEGER(),
               comment='보합 종목 수',
               existing_nullable=True)
    op.alter_column('market_indices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='생성시간',
               existing_nullable=True)
    op.drop_index('market_indices_time_idx', table_name='market_indices')
    op.drop_index('idx_market_indices_index_time', table_name='market_indices')
    op.create_index('idx_market_indices_index_time', 'market_indices', ['index_code', 'time'], unique=False)
    op.drop_index('idx_market_indices_time_desc', table_name='market_indices')
    op.create_index('idx_market_indices_time_desc', 'market_indices', ['time'], unique=False, postgresql_using='btree', postgresql_ops={'time': 'DESC'})
    op.create_table_comment(
        'market_indices',
        '시장 지수 데이터 (TimescaleDB 하이퍼테이블)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('realtime_prices', 'time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='시간 (UTC)',
               existing_nullable=False)
    op.alter_column('realtime_prices', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               comment='종목코드',
               existing_nullable=False)
    op.alter_column('realtime_prices', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='현재가',
               existing_nullable=False)
    op.alter_column('realtime_prices', 'volume',
               existing_type=sa.BIGINT(),
               comment='현재 거래량',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'bid_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='매수 1호가',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'ask_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='매도 1호가',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'bid_volume',
               existing_type=sa.BIGINT(),
               comment='매수 1호가 잔량',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'ask_volume',
               existing_type=sa.BIGINT(),
               comment='매도 1호가 잔량',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'change_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='전일대비 변동금액',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'change_rate',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='전일대비 변동률(%)',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'trading_value',
               existing_type=sa.BIGINT(),
               comment='현재 거래대금',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'accumulated_volume',
               existing_type=sa.BIGINT(),
               comment='누적 거래량',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'accumulated_value',
               existing_type=sa.BIGINT(),
               comment='누적 거래대금',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'market_status',
               existing_type=sa.VARCHAR(length=20),
               comment='시장 상태 (OPEN, CLOSE, PRE_MARKET, AFTER_MARKET)',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'is_suspended',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='거래정지 여부',
               existing_nullable=True)
    op.drop_index('idx_realtime_prices_market_status', table_name='realtime_prices', postgresql_where='(market_status IS NOT NULL)')
    op.drop_index('realtime_prices_time_idx', table_name='realtime_prices')
    op.drop_index('idx_realtime_prices_symbol_time', table_name='realtime_prices')
    op.create_index('idx_realtime_prices_symbol_time', 'realtime_prices', ['symbol', 'time'], unique=False)
    op.drop_index('idx_realtime_prices_time_desc', table_name='realtime_prices')
    op.create_index('idx_realtime_prices_time_desc', 'realtime_prices', ['time'], unique=False, postgresql_using='btree', postgresql_ops={'time': 'DESC'})
    op.create_table_comment(
        'realtime_prices',
        '실시간 가격 데이터 (TimescaleDB 하이퍼테이블)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('stock_prices', 'time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='시간 (UTC)',
               existing_nullable=False)
    op.alter_column('stock_prices', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               comment='종목코드',
               existing_nullable=False)
    op.alter_column('stock_prices', 'interval_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               comment='봉 타입 (1m, 5m, 1d)',
               existing_nullable=False)
    op.alter_column('stock_prices', 'open',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='시가',
               existing_nullable=True)
    op.alter_column('stock_prices', 'high',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='고가',
               existing_nullable=True)
    op.alter_column('stock_prices', 'low',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='저가',
               existing_nullable=True)
    op.alter_column('stock_prices', 'close',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='종가',
               existing_nullable=True)
    op.alter_column('stock_prices', 'volume',
               existing_type=sa.BIGINT(),
               comment='거래량',
               existing_nullable=True)
    op.alter_column('stock_prices', 'trading_value',
               existing_type=sa.BIGINT(),
               comment='거래대금',
               existing_nullable=True)
    op.alter_column('stock_prices', 'change_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='전일대비 변동금액',
               existing_nullable=True)
    op.alter_column('stock_prices', 'change_rate',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='전일대비 변동률(%)',
               existing_nullable=True)
    op.alter_column('stock_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='생성시간',
               existing_nullable=True)
    op.drop_index('stock_prices_time_idx', table_name='stock_prices')
    op.drop_index('idx_stock_prices_symbol_time', table_name='stock_prices')
    op.create_index('idx_stock_prices_symbol_time', 'stock_prices', ['symbol', 'time', 'interval_type'], unique=False)
    op.drop_index('idx_stock_prices_time_desc', table_name='stock_prices')
    op.create_index('idx_stock_prices_time_desc', 'stock_prices', ['time'], unique=False, postgresql_using='btree', postgresql_ops={'time': 'DESC'})
    op.create_table_comment(
        'stock_prices',
        '주가 데이터 (TimescaleDB 하이퍼테이블)',
        existing_comment=None,
        schema=None
    )
    op.add_column('supply_demand', sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='현재가'))
    op.add_column('supply_demand', sa.Column('price_change_sign', sa.String(length=5), nullable=True, comment='대비기호'))
    op.add_column('supply_demand', sa.Column('price_change', sa.Numeric(precision=12, scale=2), nullable=True, comment='전일대비'))
    op.add_column('supply_demand', sa.Column('change_rate', sa.Numeric(precision=8, scale=4), nullable=True, comment='등락율(%)'))
    op.add_column('supply_demand', sa.Column('accumulated_volume', sa.BigInteger(), nullable=True, comment='누적거래량'))
    op.add_column('supply_demand', sa.Column('accumulated_value', sa.BigInteger(), nullable=True, comment='누적거래대금'))
    op.add_column('supply_demand', sa.Column('individual_investor', sa.BigInteger(), nullable=True, comment='개인투자자'))
    op.add_column('supply_demand', sa.Column('foreign_investor', sa.BigInteger(), nullable=True, comment='외국인투자자'))
    op.add_column('supply_demand', sa.Column('institution_total', sa.BigInteger(), nullable=True, comment='기관계'))
    op.add_column('supply_demand', sa.Column('financial_investment', sa.BigInteger(), nullable=True, comment='금융투자'))
    op.add_column('supply_demand', sa.Column('insurance', sa.BigInteger(), nullable=True, comment='보험'))
    op.add_column('supply_demand', sa.Column('investment_trust', sa.BigInteger(), nullable=True, comment='투신'))
    op.add_column('supply_demand', sa.Column('other_financial', sa.BigInteger(), nullable=True, comment='기타금융'))
    op.add_column('supply_demand', sa.Column('bank', sa.BigInteger(), nullable=True, comment='은행'))
    op.add_column('supply_demand', sa.Column('pension_fund', sa.BigInteger(), nullable=True, comment='연기금등'))
    op.add_column('supply_demand', sa.Column('private_fund', sa.BigInteger(), nullable=True, comment='사모펀드'))
    op.add_column('supply_demand', sa.Column('government', sa.BigInteger(), nullable=True, comment='국가'))
    op.add_column('supply_demand', sa.Column('other_corporation', sa.BigInteger(), nullable=True, comment='기타법인'))
    op.add_column('supply_demand', sa.Column('domestic_foreign', sa.BigInteger(), nullable=True, comment='내외국인'))
    op.alter_column('supply_demand', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='날짜',
               existing_nullable=False)
    op.alter_column('supply_demand', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               comment='종목코드',
               existing_nullable=False)
    op.alter_column('supply_demand', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='생성시간',
               existing_nullable=True)
    op.drop_index('idx_supply_demand_date_desc', table_name='supply_demand')
    op.drop_index('supply_demand_date_idx', table_name='supply_demand')
    op.drop_index('idx_supply_demand_symbol_date', table_name='supply_demand')
    op.create_index('idx_supply_demand_symbol_date', 'supply_demand', ['symbol', 'date'], unique=False)
    op.create_index('idx_supply_demand_date_symbol', 'supply_demand', ['date', 'symbol'], unique=False)
    op.create_table_comment(
        'supply_demand',
        '수급 데이터 - 키움 API 종목별투자자기관별 (TimescaleDB 하이퍼테이블)',
        existing_comment=None,
        schema=None
    )
    op.drop_column('supply_demand', 'individual_amount')
    op.drop_column('supply_demand', 'foreign_amount')
    op.drop_column('supply_demand', 'foreign_cumulative')
    op.drop_column('supply_demand', 'institution_cumulative')
    op.drop_column('supply_demand', 'individual_volume')
    op.drop_column('supply_demand', 'institution_volume')
    op.drop_column('supply_demand', 'foreign_volume')
    op.drop_column('supply_demand', 'institution_amount')
    op.alter_column('trading_sessions', 'time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='시간 (UTC)',
               existing_nullable=False)
    op.alter_column('trading_sessions', 'market',
               existing_type=sa.VARCHAR(length=20),
               comment='시장 (KOSPI, KOSDAQ)',
               existing_nullable=False)
    op.alter_column('trading_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=30),
               comment='세션 타입 (MARKET_OPEN, MARKET_CLOSE, PRE_MARKET, AFTER_MARKET)',
               existing_nullable=False)
    op.alter_column('trading_sessions', 'session_status',
               existing_type=sa.VARCHAR(length=20),
               comment='세션 상태 (ACTIVE, INACTIVE)',
               existing_nullable=False)
    op.alter_column('trading_sessions', 'total_volume',
               existing_type=sa.BIGINT(),
               comment='총 거래량',
               existing_nullable=True)
    op.alter_column('trading_sessions', 'total_value',
               existing_type=sa.BIGINT(),
               comment='총 거래대금',
               existing_nullable=True)
    op.alter_column('trading_sessions', 'listed_count',
               existing_type=sa.INTEGER(),
               comment='상장 종목 수',
               existing_nullable=True)
    op.alter_column('trading_sessions', 'trading_count',
               existing_type=sa.INTEGER(),
               comment='거래 종목 수',
               existing_nullable=True)
    op.alter_column('trading_sessions', 'meta_info',
               existing_type=sa.TEXT(),
               comment='추가 정보 (JSON)',
               existing_nullable=True)
    op.alter_column('trading_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='생성시간',
               existing_nullable=True)
    op.drop_index('trading_sessions_time_idx', table_name='trading_sessions')
    op.drop_index('idx_trading_sessions_market_time', table_name='trading_sessions')
    op.create_index('idx_trading_sessions_market_time', 'trading_sessions', ['market', 'time'], unique=False)
    op.create_table_comment(
        'trading_sessions',
        '거래 세션 정보 (TimescaleDB 하이퍼테이블)',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'trading_sessions',
        existing_comment='거래 세션 정보 (TimescaleDB 하이퍼테이블)',
        schema=None
    )
    op.drop_index('idx_trading_sessions_market_time', table_name='trading_sessions')
    op.create_index('idx_trading_sessions_market_time', 'trading_sessions', ['market', sa.text('time DESC')], unique=False)
    op.create_index('trading_sessions_time_idx', 'trading_sessions', [sa.text('time DESC')], unique=False)
    op.alter_column('trading_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment=None,
               existing_comment='생성시간',
               existing_nullable=True)
    op.alter_column('trading_sessions', 'meta_info',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='추가 정보 (JSON)',
               existing_nullable=True)
    op.alter_column('trading_sessions', 'trading_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='거래 종목 수',
               existing_nullable=True)
    op.alter_column('trading_sessions', 'listed_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='상장 종목 수',
               existing_nullable=True)
    op.alter_column('trading_sessions', 'total_value',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='총 거래대금',
               existing_nullable=True)
    op.alter_column('trading_sessions', 'total_volume',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='총 거래량',
               existing_nullable=True)
    op.alter_column('trading_sessions', 'session_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='세션 상태 (ACTIVE, INACTIVE)',
               existing_nullable=False)
    op.alter_column('trading_sessions', 'session_type',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='세션 타입 (MARKET_OPEN, MARKET_CLOSE, PRE_MARKET, AFTER_MARKET)',
               existing_nullable=False)
    op.alter_column('trading_sessions', 'market',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='시장 (KOSPI, KOSDAQ)',
               existing_nullable=False)
    op.alter_column('trading_sessions', 'time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='시간 (UTC)',
               existing_nullable=False)
    op.add_column('supply_demand', sa.Column('institution_amount', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('supply_demand', sa.Column('foreign_volume', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('supply_demand', sa.Column('institution_volume', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('supply_demand', sa.Column('individual_volume', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('supply_demand', sa.Column('institution_cumulative', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('supply_demand', sa.Column('foreign_cumulative', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('supply_demand', sa.Column('foreign_amount', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('supply_demand', sa.Column('individual_amount', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_table_comment(
        'supply_demand',
        existing_comment='수급 데이터 - 키움 API 종목별투자자기관별 (TimescaleDB 하이퍼테이블)',
        schema=None
    )
    op.drop_index('idx_supply_demand_date_symbol', table_name='supply_demand')
    op.drop_index('idx_supply_demand_symbol_date', table_name='supply_demand')
    op.create_index('idx_supply_demand_symbol_date', 'supply_demand', ['symbol', sa.text('date DESC')], unique=False)
    op.create_index('supply_demand_date_idx', 'supply_demand', [sa.text('date DESC')], unique=False)
    op.create_index('idx_supply_demand_date_desc', 'supply_demand', [sa.text('date DESC')], unique=False)
    op.alter_column('supply_demand', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment=None,
               existing_comment='생성시간',
               existing_nullable=True)
    op.alter_column('supply_demand', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='종목코드',
               existing_nullable=False)
    op.alter_column('supply_demand', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='날짜',
               existing_nullable=False)
    op.drop_column('supply_demand', 'domestic_foreign')
    op.drop_column('supply_demand', 'other_corporation')
    op.drop_column('supply_demand', 'government')
    op.drop_column('supply_demand', 'private_fund')
    op.drop_column('supply_demand', 'pension_fund')
    op.drop_column('supply_demand', 'bank')
    op.drop_column('supply_demand', 'other_financial')
    op.drop_column('supply_demand', 'investment_trust')
    op.drop_column('supply_demand', 'insurance')
    op.drop_column('supply_demand', 'financial_investment')
    op.drop_column('supply_demand', 'institution_total')
    op.drop_column('supply_demand', 'foreign_investor')
    op.drop_column('supply_demand', 'individual_investor')
    op.drop_column('supply_demand', 'accumulated_value')
    op.drop_column('supply_demand', 'accumulated_volume')
    op.drop_column('supply_demand', 'change_rate')
    op.drop_column('supply_demand', 'price_change')
    op.drop_column('supply_demand', 'price_change_sign')
    op.drop_column('supply_demand', 'current_price')
    op.drop_table_comment(
        'stock_prices',
        existing_comment='주가 데이터 (TimescaleDB 하이퍼테이블)',
        schema=None
    )
    op.drop_index('idx_stock_prices_time_desc', table_name='stock_prices', postgresql_using='btree', postgresql_ops={'time': 'DESC'})
    op.create_index('idx_stock_prices_time_desc', 'stock_prices', [sa.text('time DESC')], unique=False)
    op.drop_index('idx_stock_prices_symbol_time', table_name='stock_prices')
    op.create_index('idx_stock_prices_symbol_time', 'stock_prices', ['symbol', sa.text('time DESC'), 'interval_type'], unique=False)
    op.create_index('stock_prices_time_idx', 'stock_prices', [sa.text('time DESC')], unique=False)
    op.alter_column('stock_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment=None,
               existing_comment='생성시간',
               existing_nullable=True)
    op.alter_column('stock_prices', 'change_rate',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment=None,
               existing_comment='전일대비 변동률(%)',
               existing_nullable=True)
    op.alter_column('stock_prices', 'change_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='전일대비 변동금액',
               existing_nullable=True)
    op.alter_column('stock_prices', 'trading_value',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='거래대금',
               existing_nullable=True)
    op.alter_column('stock_prices', 'volume',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='거래량',
               existing_nullable=True)
    op.alter_column('stock_prices', 'close',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='종가',
               existing_nullable=True)
    op.alter_column('stock_prices', 'low',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='저가',
               existing_nullable=True)
    op.alter_column('stock_prices', 'high',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='고가',
               existing_nullable=True)
    op.alter_column('stock_prices', 'open',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='시가',
               existing_nullable=True)
    op.alter_column('stock_prices', 'interval_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'1m'::character varying"),
               comment=None,
               existing_comment='봉 타입 (1m, 5m, 1d)',
               existing_nullable=False)
    op.alter_column('stock_prices', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='종목코드',
               existing_nullable=False)
    op.alter_column('stock_prices', 'time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='시간 (UTC)',
               existing_nullable=False)
    op.drop_table_comment(
        'realtime_prices',
        existing_comment='실시간 가격 데이터 (TimescaleDB 하이퍼테이블)',
        schema=None
    )
    op.drop_index('idx_realtime_prices_time_desc', table_name='realtime_prices', postgresql_using='btree', postgresql_ops={'time': 'DESC'})
    op.create_index('idx_realtime_prices_time_desc', 'realtime_prices', [sa.text('time DESC')], unique=False)
    op.drop_index('idx_realtime_prices_symbol_time', table_name='realtime_prices')
    op.create_index('idx_realtime_prices_symbol_time', 'realtime_prices', ['symbol', sa.text('time DESC')], unique=False)
    op.create_index('realtime_prices_time_idx', 'realtime_prices', [sa.text('time DESC')], unique=False)
    op.create_index('idx_realtime_prices_market_status', 'realtime_prices', ['market_status'], unique=False, postgresql_where='(market_status IS NOT NULL)')
    op.alter_column('realtime_prices', 'is_suspended',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='거래정지 여부',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'market_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='시장 상태 (OPEN, CLOSE, PRE_MARKET, AFTER_MARKET)',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'accumulated_value',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='누적 거래대금',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'accumulated_volume',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='누적 거래량',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'trading_value',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='현재 거래대금',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'change_rate',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment=None,
               existing_comment='전일대비 변동률(%)',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'change_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='전일대비 변동금액',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'ask_volume',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='매도 1호가 잔량',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'bid_volume',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='매수 1호가 잔량',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'ask_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='매도 1호가',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'bid_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='매수 1호가',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'volume',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='현재 거래량',
               existing_nullable=True)
    op.alter_column('realtime_prices', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='현재가',
               existing_nullable=False)
    op.alter_column('realtime_prices', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='종목코드',
               existing_nullable=False)
    op.alter_column('realtime_prices', 'time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='시간 (UTC)',
               existing_nullable=False)
    op.drop_table_comment(
        'market_indices',
        existing_comment='시장 지수 데이터 (TimescaleDB 하이퍼테이블)',
        schema=None
    )
    op.drop_index('idx_market_indices_time_desc', table_name='market_indices', postgresql_using='btree', postgresql_ops={'time': 'DESC'})
    op.create_index('idx_market_indices_time_desc', 'market_indices', [sa.text('time DESC')], unique=False)
    op.drop_index('idx_market_indices_index_time', table_name='market_indices')
    op.create_index('idx_market_indices_index_time', 'market_indices', ['index_code', sa.text('time DESC')], unique=False)
    op.create_index('market_indices_time_idx', 'market_indices', [sa.text('time DESC')], unique=False)
    op.alter_column('market_indices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment=None,
               existing_comment='생성시간',
               existing_nullable=True)
    op.alter_column('market_indices', 'unchanged_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='보합 종목 수',
               existing_nullable=True)
    op.alter_column('market_indices', 'fall_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='하락 종목 수',
               existing_nullable=True)
    op.alter_column('market_indices', 'rise_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='상승 종목 수',
               existing_nullable=True)
    op.alter_column('market_indices', 'trading_value',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='거래대금',
               existing_nullable=True)
    op.alter_column('market_indices', 'volume',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='거래량',
               existing_nullable=True)
    op.alter_column('market_indices', 'change_rate',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment=None,
               existing_comment='전일대비 변동률(%)',
               existing_nullable=True)
    op.alter_column('market_indices', 'change_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='전일대비 변동',
               existing_nullable=True)
    op.alter_column('market_indices', 'index_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='지수 값',
               existing_nullable=False)
    op.alter_column('market_indices', 'index_code',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='지수 코드 (KOSPI, KOSDAQ)',
               existing_nullable=False)
    op.alter_column('market_indices', 'time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='시간 (UTC)',
               existing_nullable=False)
    # ### end Alembic commands ### 