"""StockPrice_테이블_일봉차트_구조_업데이트_및_자동계산_트리거_추가

Revision ID: 0fb6f716225a
Revises: 016c2b084c47
Create Date: 2025-06-04 17:08:27.228542

"""
from alembic import op
import sqlalchemy as sa
import sys
import os

# timescale_utils 모듈을 import하기 위한 경로 추가
sys.path.append(os.path.dirname(os.path.dirname(__file__)))
from timescale_utils import (
    create_stock_price_auto_calculation_trigger,
    drop_stock_price_auto_calculation_trigger,
    create_stock_price_indexes,
    drop_stock_price_indexes
)


# revision identifiers, used by Alembic.
revision = '0fb6f716225a'
down_revision = '016c2b084c47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_market_indices_time_desc', table_name='market_indices')
    op.create_index('idx_market_indices_time_desc', 'market_indices', ['time'], unique=False, postgresql_using='btree', postgresql_ops={'time': 'DESC'})
    op.drop_index('idx_realtime_prices_time_desc', table_name='realtime_prices')
    op.create_index('idx_realtime_prices_time_desc', 'realtime_prices', ['time'], unique=False, postgresql_using='btree', postgresql_ops={'time': 'DESC'})
    
    # change_rate 컬럼명을 price_change_percent로 변경
    op.alter_column('stock_prices', 'change_rate',
                   new_column_name='price_change_percent',
                   existing_type=sa.Numeric(precision=8, scale=4),
                   comment='전일대비 등락율(%)',
                   existing_comment='전일대비 변동률(%)',
                   existing_nullable=True)
    
    # 새로운 컬럼들 추가
    op.add_column('stock_prices', sa.Column('volume_change', sa.BigInteger(), nullable=True, comment='전일대비 거래량 변화'))
    op.add_column('stock_prices', sa.Column('volume_change_percent', sa.Numeric(precision=8, scale=4), nullable=True, comment='전일대비 거래량 증감율(%)'))
    op.add_column('stock_prices', sa.Column('previous_close_price', sa.Numeric(precision=12, scale=2), nullable=True, comment='전일종가'))
    op.add_column('stock_prices', sa.Column('adjusted_price_type', sa.String(length=20), nullable=True, comment='수정주가구분'))
    op.add_column('stock_prices', sa.Column('adjustment_ratio', sa.Numeric(precision=10, scale=6), nullable=True, comment='수정비율'))
    op.add_column('stock_prices', sa.Column('adjusted_price_event', sa.String(length=100), nullable=True, comment='수정주가이벤트'))
    op.add_column('stock_prices', sa.Column('major_industry_type', sa.String(length=20), nullable=True, comment='대업종구분'))
    op.add_column('stock_prices', sa.Column('minor_industry_type', sa.String(length=20), nullable=True, comment='소업종구분'))
    op.add_column('stock_prices', sa.Column('stock_info', sa.String(length=100), nullable=True, comment='종목정보'))
    
    op.alter_column('stock_prices', 'close',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='종가(현재가)',
               existing_comment='종가',
               existing_nullable=True)
    op.drop_index('idx_stock_prices_time_desc', table_name='stock_prices')
    op.create_index('idx_stock_prices_time_desc', 'stock_prices', ['time'], unique=False, postgresql_using='btree', postgresql_ops={'time': 'DESC'})
    op.create_index('idx_stock_prices_date_symbol', 'stock_prices', ['time', 'symbol'], unique=False)
    op.create_table_comment(
        'stock_prices',
        '주가 데이터 - 키움 API 주식일봉차트조회 (TimescaleDB 하이퍼테이블)',
        existing_comment='주가 데이터 (TimescaleDB 하이퍼테이블)',
        schema=None
    )
    
    # 자동계산 트리거 생성
    create_stock_price_auto_calculation_trigger()
    
    # 성능 최적화 인덱스 생성
    create_stock_price_indexes()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 자동계산 트리거 삭제
    drop_stock_price_auto_calculation_trigger()
    
    # 성능 최적화 인덱스 삭제
    drop_stock_price_indexes()
    
    # price_change_percent 컬럼명을 change_rate로 복원
    op.alter_column('stock_prices', 'price_change_percent',
                   new_column_name='change_rate',
                   existing_type=sa.Numeric(precision=8, scale=4),
                   comment='전일대비 변동률(%)',
                   existing_comment='전일대비 등락율(%)',
                   existing_nullable=True)
    
    op.create_table_comment(
        'stock_prices',
        '주가 데이터 (TimescaleDB 하이퍼테이블)',
        existing_comment='주가 데이터 - 키움 API 주식일봉차트조회 (TimescaleDB 하이퍼테이블)',
        schema=None
    )
    op.drop_index('idx_stock_prices_date_symbol', table_name='stock_prices')
    op.drop_index('idx_stock_prices_time_desc', table_name='stock_prices', postgresql_using='btree', postgresql_ops={'time': 'DESC'})
    op.create_index('idx_stock_prices_time_desc', 'stock_prices', [sa.text('time DESC')], unique=False)
    op.alter_column('stock_prices', 'close',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='종가',
               existing_comment='종가(현재가)',
               existing_nullable=True)
    op.drop_column('stock_prices', 'stock_info')
    op.drop_column('stock_prices', 'minor_industry_type')
    op.drop_column('stock_prices', 'major_industry_type')
    op.drop_column('stock_prices', 'adjusted_price_event')
    op.drop_column('stock_prices', 'adjustment_ratio')
    op.drop_column('stock_prices', 'adjusted_price_type')
    op.drop_column('stock_prices', 'previous_close_price')
    op.drop_column('stock_prices', 'volume_change_percent')
    op.drop_column('stock_prices', 'volume_change')
    op.drop_index('idx_realtime_prices_time_desc', table_name='realtime_prices', postgresql_using='btree', postgresql_ops={'time': 'DESC'})
    op.create_index('idx_realtime_prices_time_desc', 'realtime_prices', [sa.text('time DESC')], unique=False)
    op.drop_index('idx_market_indices_time_desc', table_name='market_indices', postgresql_using='btree', postgresql_ops={'time': 'DESC'})
    op.create_index('idx_market_indices_time_desc', 'market_indices', [sa.text('time DESC')], unique=False)
    # ### end Alembic commands ### 