"""add_metadata_fields

Revision ID: 822a0185fc2a
Revises: 23ebdf72e09a
Create Date: 2024-12-26 13:08:09.952754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '822a0185fc2a'
down_revision: Union[str, None] = '23ebdf72e09a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_metadata', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('content_data', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('embedding_refs', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'embedding_refs')
    op.drop_column('projects', 'content_data')
    op.drop_column('projects', 'project_metadata')
    # ### end Alembic commands ###
