"""add order column to projects table

Revision ID: a66f67c23883
Revises: d2a7c8e9f123
Create Date: 2025-01-25 06:09:13.272985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66f67c23883'
down_revision: Union[str, None] = 'd2a7c8e9f123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'order')
    # ### end Alembic commands ###
