"""Category user_id 추가

Revision ID: d1c649eb56aa
Revises: 53fd394a89d7
Create Date: 2025-01-06 15:50:03.286663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection

# revision identifiers, used by Alembic.
revision: str = 'd1c649eb56aa'
down_revision: Union[str, None] = '53fd394a89d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Reflect the existing table
    bind = op.get_bind()
    inspector = reflection.Inspector.from_engine(bind)
    
    # Check if the 'user_id' column already exists
    columns = [column['name'] for column in inspector.get_columns('categories')]
    if 'user_id' not in columns:
        op.add_column('categories', sa.Column('user_id', sa.UUID(), nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'user_id')
    # ### end Alembic commands ###
