"""Add category_id to Project model

Revision ID: fddfcbfd7b50
Revises: 822a0185fc2a
Create Date: 2025-01-01 23:32:03.037853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fddfcbfd7b50'
down_revision: Union[str, None] = '822a0185fc2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'projects', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'category_id')
    # ### end Alembic commands ###
