"""초기_테이블_구조_생성

Revision ID: 21ba148ae5df
Revises: 
Create Date: 2025-06-07 10:54:52.747028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21ba148ae5df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('market_indices', 'index_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='지수 값',
               existing_nullable=False)
    op.alter_column('market_indices', 'change_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='전일대비 변동',
               existing_nullable=True)
    op.alter_column('market_indices', 'price_change_percent',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='전일대비 변동률(%)',
               existing_comment='전일대비 변동률(%) - precision 10,4',
               existing_nullable=True)
    op.alter_column('market_indices', 'volume',
               existing_type=sa.BIGINT(),
               comment='거래량',
               existing_nullable=True)
    op.alter_column('market_indices', 'trading_value',
               existing_type=sa.BIGINT(),
               comment='거래대금',
               existing_nullable=True)
    op.alter_column('market_indices', 'rise_count',
               existing_type=sa.INTEGER(),
               comment='상승 종목 수',
               existing_nullable=True)
    op.alter_column('market_indices', 'fall_count',
               existing_type=sa.INTEGER(),
               comment='하락 종목 수',
               existing_nullable=True)
    op.alter_column('market_indices', 'unchanged_count',
               existing_type=sa.INTEGER(),
               comment='보합 종목 수',
               existing_nullable=True)
    op.alter_column('market_indices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='생성시간',
               existing_nullable=True)
    op.drop_index('market_indices_time_idx', table_name='market_indices')
    op.drop_index('idx_market_indices_index_time', table_name='market_indices')
    op.create_index('idx_market_indices_index_time', 'market_indices', ['index_code', 'time'], unique=False)
    op.drop_index('idx_market_indices_time_desc', table_name='market_indices')
    op.create_index('idx_market_indices_time_desc', 'market_indices', ['time'], unique=False, postgresql_using='btree', postgresql_ops={'time': 'DESC'})
    op.create_table_comment(
        'market_indices',
        '시장 지수 데이터 (TimescaleDB 하이퍼테이블)',
        existing_comment='시장 지수 데이터 - TimescaleDB 하이퍼테이블',
        schema=None
    )
    op.alter_column('stock_prices', 'interval_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               comment='봉 타입 (1m, 5m, 1d)',
               existing_nullable=False)
    op.alter_column('stock_prices', 'open',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='시가',
               existing_nullable=True)
    op.alter_column('stock_prices', 'high',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='고가',
               existing_nullable=True)
    op.alter_column('stock_prices', 'low',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='저가',
               existing_nullable=True)
    op.alter_column('stock_prices', 'close',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='종가(현재가)',
               existing_nullable=True)
    op.alter_column('stock_prices', 'volume',
               existing_type=sa.BIGINT(),
               comment='거래량',
               existing_nullable=True)
    op.alter_column('stock_prices', 'trading_value',
               existing_type=sa.BIGINT(),
               comment='거래대금',
               existing_nullable=True)
    op.alter_column('stock_prices', 'change_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='전일대비 변동금액',
               existing_nullable=True)
    op.alter_column('stock_prices', 'price_change_percent',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='전일대비 등락율(%)',
               existing_comment='전일대비 등락율(%) - precision 10,4',
               existing_nullable=True)
    op.alter_column('stock_prices', 'volume_change',
               existing_type=sa.BIGINT(),
               comment='전일대비 거래량 변화',
               existing_nullable=True)
    op.alter_column('stock_prices', 'volume_change_percent',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='전일대비 거래량 증감율(%)',
               existing_comment='전일대비 거래량 증감율(%) - precision 10,4',
               existing_nullable=True)
    op.alter_column('stock_prices', 'previous_close_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='전일종가',
               existing_nullable=True)
    op.alter_column('stock_prices', 'adjusted_price_type',
               existing_type=sa.VARCHAR(length=20),
               comment='수정주가구분',
               existing_nullable=True)
    op.alter_column('stock_prices', 'adjustment_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               comment='수정비율',
               existing_nullable=True)
    op.alter_column('stock_prices', 'adjusted_price_event',
               existing_type=sa.VARCHAR(length=100),
               comment='수정주가이벤트',
               existing_nullable=True)
    op.alter_column('stock_prices', 'major_industry_type',
               existing_type=sa.VARCHAR(length=20),
               comment='대업종구분',
               existing_nullable=True)
    op.alter_column('stock_prices', 'minor_industry_type',
               existing_type=sa.VARCHAR(length=20),
               comment='소업종구분',
               existing_nullable=True)
    op.alter_column('stock_prices', 'stock_info',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               comment='종목정보',
               existing_nullable=True)
    op.alter_column('stock_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='생성시간',
               existing_nullable=True)
    op.drop_index('stock_prices_time_idx', table_name='stock_prices')
    op.drop_index('idx_stock_prices_symbol_time', table_name='stock_prices')
    op.create_index('idx_stock_prices_symbol_time', 'stock_prices', ['symbol', 'time', 'interval_type'], unique=False)
    op.drop_index('idx_stock_prices_time_desc', table_name='stock_prices')
    op.create_index('idx_stock_prices_time_desc', 'stock_prices', ['time'], unique=False, postgresql_using='btree', postgresql_ops={'time': 'DESC'})
    op.create_index('idx_stock_prices_date_symbol', 'stock_prices', ['time', 'symbol'], unique=False)
    op.create_table_comment(
        'stock_prices',
        '주가 데이터 - 키움 API 주식일봉차트조회 (TimescaleDB 하이퍼테이블)',
        existing_comment='주가 데이터 - TimescaleDB 하이퍼테이블',
        schema=None
    )
    op.drop_column('stock_prices', 'updated_at')
    op.alter_column('supply_demand', 'current_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='현재가',
               existing_nullable=True)
    op.alter_column('supply_demand', 'price_change_sign',
               existing_type=sa.VARCHAR(length=5),
               comment='대비기호',
               existing_nullable=True)
    op.alter_column('supply_demand', 'price_change',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='전일대비',
               existing_nullable=True)
    op.alter_column('supply_demand', 'price_change_percent',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='등락율(%)',
               existing_comment='등락율(%) - precision 10,4',
               existing_nullable=True)
    op.alter_column('supply_demand', 'accumulated_volume',
               existing_type=sa.BIGINT(),
               comment='누적거래량',
               existing_nullable=True)
    op.alter_column('supply_demand', 'accumulated_value',
               existing_type=sa.BIGINT(),
               comment='누적거래대금',
               existing_nullable=True)
    op.alter_column('supply_demand', 'individual_investor',
               existing_type=sa.BIGINT(),
               comment='개인투자자',
               existing_nullable=True)
    op.alter_column('supply_demand', 'foreign_investor',
               existing_type=sa.BIGINT(),
               comment='외국인투자자',
               existing_nullable=True)
    op.alter_column('supply_demand', 'institution_total',
               existing_type=sa.BIGINT(),
               comment='기관계',
               existing_nullable=True)
    op.alter_column('supply_demand', 'financial_investment',
               existing_type=sa.BIGINT(),
               comment='금융투자',
               existing_nullable=True)
    op.alter_column('supply_demand', 'insurance',
               existing_type=sa.BIGINT(),
               comment='보험',
               existing_nullable=True)
    op.alter_column('supply_demand', 'investment_trust',
               existing_type=sa.BIGINT(),
               comment='투신',
               existing_nullable=True)
    op.alter_column('supply_demand', 'other_financial',
               existing_type=sa.BIGINT(),
               comment='기타금융',
               existing_nullable=True)
    op.alter_column('supply_demand', 'bank',
               existing_type=sa.BIGINT(),
               comment='은행',
               existing_nullable=True)
    op.alter_column('supply_demand', 'pension_fund',
               existing_type=sa.BIGINT(),
               comment='연기금등',
               existing_nullable=True)
    op.alter_column('supply_demand', 'private_fund',
               existing_type=sa.BIGINT(),
               comment='사모펀드',
               existing_nullable=True)
    op.alter_column('supply_demand', 'government',
               existing_type=sa.BIGINT(),
               comment='국가',
               existing_nullable=True)
    op.alter_column('supply_demand', 'other_corporation',
               existing_type=sa.BIGINT(),
               comment='기타법인',
               existing_nullable=True)
    op.alter_column('supply_demand', 'domestic_foreign',
               existing_type=sa.BIGINT(),
               comment='내외국인',
               existing_nullable=True)
    op.alter_column('supply_demand', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='생성시간',
               existing_nullable=True)
    op.drop_index('idx_supply_demand_date_desc', table_name='supply_demand')
    op.drop_index('supply_demand_date_idx', table_name='supply_demand')
    op.drop_index('idx_supply_demand_symbol_date', table_name='supply_demand')
    op.create_index('idx_supply_demand_symbol_date', 'supply_demand', ['symbol', 'date'], unique=False)
    op.create_index('idx_supply_demand_date_symbol', 'supply_demand', ['date', 'symbol'], unique=False)
    op.create_table_comment(
        'supply_demand',
        '수급 데이터 - 키움 API 종목별투자자기관별 (TimescaleDB 하이퍼테이블)',
        existing_comment='수급 데이터 - TimescaleDB 하이퍼테이블',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'supply_demand',
        '수급 데이터 - TimescaleDB 하이퍼테이블',
        existing_comment='수급 데이터 - 키움 API 종목별투자자기관별 (TimescaleDB 하이퍼테이블)',
        schema=None
    )
    op.drop_index('idx_supply_demand_date_symbol', table_name='supply_demand')
    op.drop_index('idx_supply_demand_symbol_date', table_name='supply_demand')
    op.create_index('idx_supply_demand_symbol_date', 'supply_demand', ['symbol', sa.text('date DESC')], unique=False)
    op.create_index('supply_demand_date_idx', 'supply_demand', [sa.text('date DESC')], unique=False)
    op.create_index('idx_supply_demand_date_desc', 'supply_demand', [sa.text('date DESC')], unique=False)
    op.alter_column('supply_demand', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment=None,
               existing_comment='생성시간',
               existing_nullable=True)
    op.alter_column('supply_demand', 'domestic_foreign',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='내외국인',
               existing_nullable=True)
    op.alter_column('supply_demand', 'other_corporation',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='기타법인',
               existing_nullable=True)
    op.alter_column('supply_demand', 'government',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='국가',
               existing_nullable=True)
    op.alter_column('supply_demand', 'private_fund',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='사모펀드',
               existing_nullable=True)
    op.alter_column('supply_demand', 'pension_fund',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='연기금등',
               existing_nullable=True)
    op.alter_column('supply_demand', 'bank',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='은행',
               existing_nullable=True)
    op.alter_column('supply_demand', 'other_financial',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='기타금융',
               existing_nullable=True)
    op.alter_column('supply_demand', 'investment_trust',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='투신',
               existing_nullable=True)
    op.alter_column('supply_demand', 'insurance',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='보험',
               existing_nullable=True)
    op.alter_column('supply_demand', 'financial_investment',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='금융투자',
               existing_nullable=True)
    op.alter_column('supply_demand', 'institution_total',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='기관계',
               existing_nullable=True)
    op.alter_column('supply_demand', 'foreign_investor',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='외국인투자자',
               existing_nullable=True)
    op.alter_column('supply_demand', 'individual_investor',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='개인투자자',
               existing_nullable=True)
    op.alter_column('supply_demand', 'accumulated_value',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='누적거래대금',
               existing_nullable=True)
    op.alter_column('supply_demand', 'accumulated_volume',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='누적거래량',
               existing_nullable=True)
    op.alter_column('supply_demand', 'price_change_percent',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='등락율(%) - precision 10,4',
               existing_comment='등락율(%)',
               existing_nullable=True)
    op.alter_column('supply_demand', 'price_change',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='전일대비',
               existing_nullable=True)
    op.alter_column('supply_demand', 'price_change_sign',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='대비기호',
               existing_nullable=True)
    op.alter_column('supply_demand', 'current_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='현재가',
               existing_nullable=True)
    op.add_column('stock_prices', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.create_table_comment(
        'stock_prices',
        '주가 데이터 - TimescaleDB 하이퍼테이블',
        existing_comment='주가 데이터 - 키움 API 주식일봉차트조회 (TimescaleDB 하이퍼테이블)',
        schema=None
    )
    op.drop_index('idx_stock_prices_date_symbol', table_name='stock_prices')
    op.drop_index('idx_stock_prices_time_desc', table_name='stock_prices', postgresql_using='btree', postgresql_ops={'time': 'DESC'})
    op.create_index('idx_stock_prices_time_desc', 'stock_prices', [sa.text('time DESC')], unique=False)
    op.drop_index('idx_stock_prices_symbol_time', table_name='stock_prices')
    op.create_index('idx_stock_prices_symbol_time', 'stock_prices', ['symbol', sa.text('time DESC'), 'interval_type'], unique=False)
    op.create_index('stock_prices_time_idx', 'stock_prices', [sa.text('time DESC')], unique=False)
    op.alter_column('stock_prices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment=None,
               existing_comment='생성시간',
               existing_nullable=True)
    op.alter_column('stock_prices', 'stock_info',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               comment=None,
               existing_comment='종목정보',
               existing_nullable=True)
    op.alter_column('stock_prices', 'minor_industry_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='소업종구분',
               existing_nullable=True)
    op.alter_column('stock_prices', 'major_industry_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='대업종구분',
               existing_nullable=True)
    op.alter_column('stock_prices', 'adjusted_price_event',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='수정주가이벤트',
               existing_nullable=True)
    op.alter_column('stock_prices', 'adjustment_ratio',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               comment=None,
               existing_comment='수정비율',
               existing_nullable=True)
    op.alter_column('stock_prices', 'adjusted_price_type',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='수정주가구분',
               existing_nullable=True)
    op.alter_column('stock_prices', 'previous_close_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='전일종가',
               existing_nullable=True)
    op.alter_column('stock_prices', 'volume_change_percent',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='전일대비 거래량 증감율(%) - precision 10,4',
               existing_comment='전일대비 거래량 증감율(%)',
               existing_nullable=True)
    op.alter_column('stock_prices', 'volume_change',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='전일대비 거래량 변화',
               existing_nullable=True)
    op.alter_column('stock_prices', 'price_change_percent',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='전일대비 등락율(%) - precision 10,4',
               existing_comment='전일대비 등락율(%)',
               existing_nullable=True)
    op.alter_column('stock_prices', 'change_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='전일대비 변동금액',
               existing_nullable=True)
    op.alter_column('stock_prices', 'trading_value',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='거래대금',
               existing_nullable=True)
    op.alter_column('stock_prices', 'volume',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='거래량',
               existing_nullable=True)
    op.alter_column('stock_prices', 'close',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='종가(현재가)',
               existing_nullable=True)
    op.alter_column('stock_prices', 'low',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='저가',
               existing_nullable=True)
    op.alter_column('stock_prices', 'high',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='고가',
               existing_nullable=True)
    op.alter_column('stock_prices', 'open',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='시가',
               existing_nullable=True)
    op.alter_column('stock_prices', 'interval_type',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'1d'::character varying"),
               comment=None,
               existing_comment='봉 타입 (1m, 5m, 1d)',
               existing_nullable=False)
    op.create_table_comment(
        'market_indices',
        '시장 지수 데이터 - TimescaleDB 하이퍼테이블',
        existing_comment='시장 지수 데이터 (TimescaleDB 하이퍼테이블)',
        schema=None
    )
    op.drop_index('idx_market_indices_time_desc', table_name='market_indices', postgresql_using='btree', postgresql_ops={'time': 'DESC'})
    op.create_index('idx_market_indices_time_desc', 'market_indices', [sa.text('time DESC')], unique=False)
    op.drop_index('idx_market_indices_index_time', table_name='market_indices')
    op.create_index('idx_market_indices_index_time', 'market_indices', ['index_code', sa.text('time DESC')], unique=False)
    op.create_index('market_indices_time_idx', 'market_indices', [sa.text('time DESC')], unique=False)
    op.alter_column('market_indices', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment=None,
               existing_comment='생성시간',
               existing_nullable=True)
    op.alter_column('market_indices', 'unchanged_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='보합 종목 수',
               existing_nullable=True)
    op.alter_column('market_indices', 'fall_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='하락 종목 수',
               existing_nullable=True)
    op.alter_column('market_indices', 'rise_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='상승 종목 수',
               existing_nullable=True)
    op.alter_column('market_indices', 'trading_value',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='거래대금',
               existing_nullable=True)
    op.alter_column('market_indices', 'volume',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='거래량',
               existing_nullable=True)
    op.alter_column('market_indices', 'price_change_percent',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               comment='전일대비 변동률(%) - precision 10,4',
               existing_comment='전일대비 변동률(%)',
               existing_nullable=True)
    op.alter_column('market_indices', 'change_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='전일대비 변동',
               existing_nullable=True)
    op.alter_column('market_indices', 'index_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='지수 값',
               existing_nullable=False)
    # ### end Alembic commands ### 