"""create web search caching table

Revision ID: 0962e977b4cc
Revises: a817588d0c80
Create Date: 2025-05-19 03:12:09.153768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '0962e977b4cc'
down_revision: Union[str, None] = 'a817588d0c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# OpenAI text-embedding-3-large 기본 차원 수
EMBEDDING_DIM = 3072

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('web_search_query_cache',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('query', sa.Text(), nullable=False),
        sa.Column('stock_code', sa.String(length=20), nullable=True),
        sa.Column('stock_name', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='생성 시간 (Asia/Seoul)'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='수정 시간 (Asia/Seoul)'),
        sa.Column('hit_count', sa.Integer(), nullable=False, server_default=sa.text('0')),
        sa.Column('last_hit_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='최근 hit 시간 (Asia/Seoul)'),
        sa.Column('embedding', Vector(EMBEDDING_DIM), nullable=True),        
        sa.PrimaryKeyConstraint('id'),
        schema='stockeasy'
    )
    
    op.create_index(
        op.f('ix_stockeasy_web_search_query_cache_stock_code'), 
        'web_search_query_cache', 
        ['stock_code'], 
        unique=False, 
        schema='stockeasy'
    )
    
    op.create_table('web_search_result_cache',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('query_cache_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.Text(), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('url', sa.Text(), nullable=True),
        sa.Column('search_query', sa.Text(), nullable=True),
        sa.Column('search_date', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='생성 시간 (Asia/Seoul)'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='수정 시간 (Asia/Seoul)'),
        sa.ForeignKeyConstraint(['query_cache_id'], ['stockeasy.web_search_query_cache.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='stockeasy'
    )
    
    op.create_index(
        op.f('ix_stockeasy_web_search_result_cache_query_cache_id'), 
        'web_search_result_cache', 
        ['query_cache_id'], 
        unique=False, 
        schema='stockeasy'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stockeasy_web_search_result_cache_query_cache_id'), table_name='web_search_result_cache', schema='stockeasy')
    op.drop_table('web_search_result_cache', schema='stockeasy')
    op.drop_index(op.f('ix_stockeasy_web_search_query_cache_stock_code'), table_name='web_search_query_cache', schema='stockeasy')
    op.drop_table('web_search_query_cache', schema='stockeasy')
    # ### end Alembic commands ###
