"""add oauth columns to user model

Revision ID: 1246e8e10aa8
Revises: fddfcbfd7b50
Create Date: 2025-01-03 18:11:32.158991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1246e8e10aa8'
down_revision: Union[str, None] = 'fddfcbfd7b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=20), nullable=False))
    op.add_column('users', sa.Column('oauth_provider_id', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oauth_provider_id')
    op.drop_column('users', 'oauth_provider')
    # ### end Alembic commands ###
