"""telegram_message - collected_at

Revision ID: 136454ba022c
Revises: fix_all_datetime_fields
Create Date: 2025-02-20 18:34:57.760986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '136454ba022c'
down_revision: Union[str, None] = 'fix_all_datetime_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('document_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('document_chunks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('table_histories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('table_histories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('telegram_messages', 'collected_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('telegram_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('telegram_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('users', 'oauth_provider',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'oauth_provider_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='생성 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('users', 'oauth_provider_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'oauth_provider',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('telegram_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('telegram_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('telegram_messages', 'collected_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('table_histories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('table_histories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('document_chunks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('document_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수정 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='생성 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    # ### end Alembic commands ###
