"""Remove updated_at column from user_statistics table

Revision ID: 155e1b85beb8
Revises: c10dab477f4c
Create Date: 2025-06-23 02:29:54.333615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155e1b85beb8'
down_revision: Union[str, None] = 'c10dab477f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_statistics', 'updated_at', schema='stockeasy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_statistics', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True), schema='stockeasy')
    # ### end Alembic commands ###
