"""add profile image url in user table

Revision ID: 1711657a9b73
Revises: f4432679b9f6
Create Date: 2025-04-07 21:38:45.262502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision: str = '1711657a9b73'
down_revision: Union[str, None] = 'f4432679b9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 테이블 존재 여부 확인을 위한 인스펙터 생성
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    
    # 'profile_image' 컬럼이 'users' 테이블에 존재하는지 확인
    columns = [col['name'] for col in inspector.get_columns('users')]
    if 'profile_image' not in columns:
        op.add_column('users', sa.Column('profile_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###
