"""Add Telegram Table2

Revision ID: 1b6fa026e23e
Revises: 25a2f492559a
Create Date: 2025-02-11 21:12:37.869967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6fa026e23e'
down_revision: Union[str, None] = '25a2f492559a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('channel_title', sa.String(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=True),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('is_embedded', sa.Boolean(), nullable=False),
    sa.Column('has_media', sa.Boolean(), nullable=False),
    sa.Column('has_document', sa.Boolean(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=True),
    sa.Column('document_gcs_path', sa.String(), nullable=True),
    sa.Column('document_mime_type', sa.String(), nullable=True),
    sa.Column('document_size', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_messages_channel_id'), 'telegram_messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_telegram_messages_id'), 'telegram_messages', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_messages_message_id'), 'telegram_messages', ['message_id'], unique=False)
    op.create_index('ix_telegram_messages_msg_channel', 'telegram_messages', ['message_id', 'channel_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telegram_messages_msg_channel', table_name='telegram_messages')
    op.drop_index(op.f('ix_telegram_messages_message_id'), table_name='telegram_messages')
    op.drop_index(op.f('ix_telegram_messages_id'), table_name='telegram_messages')
    op.drop_index(op.f('ix_telegram_messages_channel_id'), table_name='telegram_messages')
    op.drop_table('telegram_messages')
    # ### end Alembic commands ###
