"""update_datetime_fields_to_seoul_timezone2

Revision ID: 2a12d4680316
Revises: 7c1dfd08a779
Create Date: 2025-02-20 16:43:26.531159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a12d4680316'
down_revision: Union[str, None] = '7c1dfd08a779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
