"""update_alltables_datetime_fields_to_seoul_timezone

Revision ID: 42ec716857fb
Revises: 9a1ebe1109fd
Create Date: 2025-02-20 17:41:55.025615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42ec716857fb'
down_revision: Union[str, None] = '9a1ebe1109fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 트리거 함수가 없다면 생성
    op.execute("""
        CREATE OR REPLACE FUNCTION trigger_set_timestamp_with_timezone()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP);
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # users 테이블 업데이트
    op.execute("""
        -- users 테이블의 NULL 값 처리
        UPDATE users 
        SET created_at = TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP),
            updated_at = TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)
        WHERE created_at IS NULL OR updated_at IS NULL;

        -- users 테이블의 timestamp 필드를 timestamptz로 변경
        ALTER TABLE users 
        ALTER COLUMN created_at TYPE timestamptz 
        USING created_at AT TIME ZONE 'UTC',
        ALTER COLUMN created_at SET DEFAULT TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP),
        ALTER COLUMN updated_at TYPE timestamptz 
        USING updated_at AT TIME ZONE 'UTC',
        ALTER COLUMN updated_at SET DEFAULT TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP);

        -- users 테이블에 트리거 추가
        DROP TRIGGER IF EXISTS update_users_updated_at ON users;
        CREATE TRIGGER update_users_updated_at
            BEFORE UPDATE ON users
            FOR EACH ROW
            EXECUTE FUNCTION trigger_set_timestamp_with_timezone();
    """)

    # sessions 테이블 업데이트
    op.execute("""
        -- sessions 테이블의 timestamp 필드를 timestamptz로 변경
        ALTER TABLE sessions 
        ALTER COLUMN created_at TYPE timestamptz 
        USING created_at AT TIME ZONE 'UTC',
        ALTER COLUMN created_at SET DEFAULT TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP),
        ALTER COLUMN updated_at TYPE timestamptz 
        USING updated_at AT TIME ZONE 'UTC',
        ALTER COLUMN updated_at SET DEFAULT TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP);

        -- sessions 테이블의 NULL 값 처리
        UPDATE sessions 
        SET created_at = TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP),
            updated_at = TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)
        WHERE created_at IS NULL OR updated_at IS NULL;

        -- sessions 테이블에 트리거 추가
        DROP TRIGGER IF EXISTS update_sessions_updated_at ON sessions;
        CREATE TRIGGER update_sessions_updated_at
            BEFORE UPDATE ON sessions
            FOR EACH ROW
            EXECUTE FUNCTION trigger_set_timestamp_with_timezone();
    """)

    # table_histories 테이블 업데이트
    op.execute("""
        -- table_histories의 NULL 값 처리
        UPDATE table_histories 
        SET updated_at = created_at 
        WHERE updated_at IS NULL;

        -- table_histories 테이블의 timestamp 필드를 timestamptz로 변경
        ALTER TABLE table_histories 
        ALTER COLUMN updated_at TYPE timestamptz 
        USING updated_at AT TIME ZONE 'UTC',
        ALTER COLUMN updated_at SET DEFAULT TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP);

        -- table_histories 테이블에 트리거 추가
        DROP TRIGGER IF EXISTS update_table_histories_updated_at ON table_histories;
        CREATE TRIGGER update_table_histories_updated_at
            BEFORE UPDATE ON table_histories
            FOR EACH ROW
            EXECUTE FUNCTION trigger_set_timestamp_with_timezone();
    """)

    # telegram_messages 테이블 업데이트
    op.execute("""
        -- telegram_messages 테이블의 timestamp 필드를 timestamptz로 변경
        ALTER TABLE telegram_messages 
        ALTER COLUMN created_at TYPE timestamptz 
        USING created_at AT TIME ZONE 'UTC',
        ALTER COLUMN created_at SET DEFAULT TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP);

        -- telegram_messages 테이블에 트리거 추가
        DROP TRIGGER IF EXISTS update_telegram_messages_updated_at ON telegram_messages;
        CREATE TRIGGER update_telegram_messages_updated_at
            BEFORE UPDATE ON telegram_messages
            FOR EACH ROW
            EXECUTE FUNCTION trigger_set_timestamp_with_timezone();
    """)

    # Add message_created_at column to telegram_messages
    op.add_column('telegram_messages', sa.Column('message_created_at', sa.DateTime(timezone=True), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop triggers
    op.execute("""
        DROP TRIGGER IF EXISTS update_users_updated_at ON users;
        DROP TRIGGER IF EXISTS update_sessions_updated_at ON sessions;
        DROP TRIGGER IF EXISTS update_table_histories_updated_at ON table_histories;
        DROP TRIGGER IF EXISTS update_telegram_messages_updated_at ON telegram_messages;
    """)
    
    # Revert users table
    op.execute("""
        ALTER TABLE users 
        ALTER COLUMN created_at TYPE timestamp 
        USING created_at AT TIME ZONE 'Asia/Seoul',
        ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
        ALTER COLUMN updated_at TYPE timestamp 
        USING updated_at AT TIME ZONE 'Asia/Seoul',
        ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
    """)

    # Revert sessions table
    op.execute("""
        ALTER TABLE sessions 
        ALTER COLUMN created_at TYPE timestamp 
        USING created_at AT TIME ZONE 'Asia/Seoul',
        ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
        ALTER COLUMN updated_at TYPE timestamp 
        USING updated_at AT TIME ZONE 'Asia/Seoul',
        ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;
    """)

    # Revert table_histories table
    op.execute("""
        ALTER TABLE table_histories 
        ALTER COLUMN updated_at TYPE timestamp 
        USING updated_at AT TIME ZONE 'Asia/Seoul',
        ALTER COLUMN updated_at DROP DEFAULT;
    """)

    # Revert telegram_messages table
    op.execute("""
        ALTER TABLE telegram_messages 
        ALTER COLUMN created_at TYPE timestamp 
        USING created_at AT TIME ZONE 'Asia/Seoul',
        ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;
    """)

    # Drop message_created_at column from telegram_messages
    op.drop_column('telegram_messages', 'message_created_at')

    # Drop trigger function
    op.execute("DROP FUNCTION IF EXISTS trigger_set_timestamp_with_timezone();")

    # ### end Alembic commands ###
