"""Create user_statistics table

Revision ID: 49a0ef9f1e8e
Revises: df8263098851
Create Date: 2025-06-23 00:19:12.222624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a0ef9f1e8e'
down_revision: Union[str, None] = 'df8263098851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stat_type', sa.String(length=20), nullable=False, comment='통계 유형 (HOURLY, DAILY, MONTHLY)'),
    sa.Column('report_at', sa.DateTime(), nullable=False, comment='통계 집계 기준 시각'),
    sa.Column('total_users', sa.Integer(), nullable=False, comment='누적 전체 사용자 수'),
    sa.Column('new_users', sa.Integer(), nullable=False, comment='해당 기간 신규 가입자 수'),
    sa.Column('active_users', sa.Integer(), nullable=False, comment='해당 기간 활성 사용자 수'),
    sa.Column('total_chat_sessions', sa.Integer(), nullable=False, comment='누적 전체 채팅 세션 수'),
    sa.Column('new_chat_sessions', sa.Integer(), nullable=False, comment='해당 기간 신규 채팅 세션 수'),
    sa.Column('sessions_per_user', sa.Float(), nullable=True, comment='전체채팅/전체사용자'),
    sa.Column('sessions_per_active_user', sa.Float(), nullable=True, comment='오늘채팅/오늘사용자'),
    sa.Column('active_user_percentage', sa.Float(), nullable=True, comment='오늘사용자/전체사용자'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='레코드 생성 시각'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='수정 시간 (Asia/Seoul)'),
    sa.PrimaryKeyConstraint('id'),
    schema='stockeasy'
    )
    op.create_index(op.f('ix_stockeasy_user_statistics_id'), 'user_statistics', ['id'], unique=False, schema='stockeasy')
    op.create_index(op.f('ix_stockeasy_user_statistics_report_at'), 'user_statistics', ['report_at'], unique=False, schema='stockeasy')
    op.create_index(op.f('ix_stockeasy_user_statistics_stat_type'), 'user_statistics', ['stat_type'], unique=False, schema='stockeasy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stockeasy_user_statistics_stat_type'), table_name='user_statistics', schema='stockeasy')
    op.drop_index(op.f('ix_stockeasy_user_statistics_report_at'), table_name='user_statistics', schema='stockeasy')
    op.drop_index(op.f('ix_stockeasy_user_statistics_id'), table_name='user_statistics', schema='stockeasy')
    op.drop_table('user_statistics', schema='stockeasy')
    # ### end Alembic commands ###
