"""extend_chat_session_title_length_to_1000

Revision ID: 4e0862caa77d
Revises: 0962e977b4cc
Create Date: 2025-05-26 08:51:29.547671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e0862caa77d'
down_revision: Union[str, None] = '0962e977b4cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 채팅 세션 제목 길이를 255자에서 1000자로 확장
    op.alter_column('stockeasy_chat_sessions', 'title',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.VARCHAR(length=1000),
                    existing_nullable=False,
                    schema='stockeasy')
    
    # 공유 채팅 세션 제목 길이도 255자에서 1000자로 확장
    op.alter_column('stockeasy_shared_chat_sessions', 'title',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.VARCHAR(length=1000),
                    existing_nullable=False,
                    schema='stockeasy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 공유 채팅 세션 제목 길이를 1000자에서 255자로 되돌림
    op.alter_column('stockeasy_shared_chat_sessions', 'title',
                    existing_type=sa.VARCHAR(length=1000),
                    type_=sa.VARCHAR(length=255),
                    existing_nullable=False,
                    schema='stockeasy')
    
    # 채팅 세션 제목 길이를 1000자에서 255자로 되돌림
    op.alter_column('stockeasy_chat_sessions', 'title',
                    existing_type=sa.VARCHAR(length=1000),
                    type_=sa.VARCHAR(length=255),
                    existing_nullable=False,
                    schema='stockeasy')
    # ### end Alembic commands ###
