"""create_user_rs_favorites_table

Revision ID: 50c2d632bbc5
Revises: f68e5e33f876
Create Date: 2025-07-22 00:13:03.311306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c2d632bbc5'
down_revision: Union[str, None] = 'f68e5e33f876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_rs_favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='stockeasy'
    )
    op.create_index(op.f('ix_stockeasy_user_rs_favorites_user_id'), 'user_rs_favorites', ['user_id'], unique=False, schema='stockeasy')
    op.create_index('ix_user_rs_favorites_user_stock_unique', 'user_rs_favorites', ['user_id', 'stock_code'], unique=True, schema='stockeasy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_rs_favorites_user_stock_unique', table_name='user_rs_favorites', schema='stockeasy')
    op.drop_index(op.f('ix_stockeasy_user_rs_favorites_user_id'), table_name='user_rs_favorites', schema='stockeasy')
    op.drop_table('user_rs_favorites', schema='stockeasy')
    # ### end Alembic commands ###
