"""Session Table의 session id 삭제. 그냥 id 이용. id.index=True

Revision ID: 624de6dc63e2
Revises: 05157a1b9591
Create Date: 2025-02-04 20:18:37.860117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '624de6dc63e2'
down_revision: Union[str, None] = '05157a1b9591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    # ### end Alembic commands ###
