"""update_datetime_fields_to_seoul_timezone2

Revision ID: 735d45ecd5a2
Revises: 2a12d4680316
Create Date: 2025-02-20 16:51:27.877342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735d45ecd5a2'
down_revision: Union[str, None] = '2a12d4680316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
