"""Add components column to StockChatMessage and make content nullable

Revision ID: 77adc861e89f
Revises: f697c6ad55a3
Create Date: 2025-04-29 21:48:23.152827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77adc861e89f'
down_revision: Union[str, None] = 'f697c6ad55a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. StockChatMessage 테이블의 content 컬럼을 nullable로 변경
    op.alter_column('stockeasy_chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='stockeasy')
    
    # 2. StockChatMessage 테이블에 components 컬럼 추가
    op.add_column('stockeasy_chat_messages',
               sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='구조화된 메시지 컴포넌트 배열 (제목, 단락, 차트, 테이블 등)'),
               schema='stockeasy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. StockChatMessage 테이블에서 components 컬럼 제거
    op.drop_column('stockeasy_chat_messages', 'components', schema='stockeasy')
    
    # 2. StockChatMessage 테이블의 content 컬럼을 다시 NOT NULL로 변경
    op.alter_column('stockeasy_chat_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='stockeasy')
    # ### end Alembic commands ###
