"""DocumentChunk id 기본값 생성

Revision ID: 7bf272c79fd1
Revises: 998d56a6c28b
Create Date: 2025-02-24 22:19:59.726496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf272c79fd1'
down_revision: Union[str, None] = '998d56a6c28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
