"""restructure Documentchunk table

Revision ID: 998d56a6c28b
Revises: 136454ba022c
Create Date: 2025-02-24 21:47:48.039110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '998d56a6c28b'
down_revision: Union[str, None] = '136454ba022c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('chunk_index', sa.Integer(), nullable=False))
    op.add_column('document_chunks', sa.Column('chunk_content', sa.Text(), nullable=False))
    op.create_unique_constraint('uq_document_chunk_index', 'document_chunks', ['document_id', 'chunk_index'])
    op.drop_column('document_chunks', 'content')
    op.alter_column('table_histories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_comment='수정 시간 (Asia/Seoul)',
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('table_histories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_comment='수정 시간 (Asia/Seoul)',
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"))
    op.add_column('document_chunks', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_document_chunk_index', 'document_chunks', type_='unique')
    op.drop_column('document_chunks', 'chunk_content')
    op.drop_column('document_chunks', 'chunk_index')
    # ### end Alembic commands ###
