"""add column stockeasy_chat_message. expert

Revision ID: a1d80e8c029a
Revises: 1711657a9b73
Create Date: 2025-04-09 14:43:16.597002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect, Inspector

# revision identifiers, used by Alembic.
revision: str = 'a1d80e8c029a'
down_revision: Union[str, None] = '1711657a9b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # stockeasy_chat_messages 테이블이 존재하는지 확인
    tables = inspector.get_table_names(schema='stockeasy')
    if 'stockeasy_chat_messages' in tables:
        # 칼럼이 이미 존재하는지 확인
        columns = [col['name'] for col in inspector.get_columns('stockeasy_chat_messages', schema='stockeasy')]
        if 'content_expert' not in columns:
            # content_expert 칼럼 추가
            op.add_column(
                'stockeasy_chat_messages',
                sa.Column('content_expert', sa.Text(), nullable=True, comment='전문가 메시지 텍스트 내용'),
                schema='stockeasy'
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # stockeasy_chat_messages 테이블이 존재하는지 확인
    tables = inspector.get_table_names(schema='stockeasy')
    if 'stockeasy_chat_messages' in tables:
        # 칼럼이 존재하는지 확인
        columns = [col['name'] for col in inspector.get_columns('stockeasy_chat_messages', schema='stockeasy')]
        if 'content_expert' in columns:
            # content_expert 칼럼 삭제
            op.drop_column('stockeasy_chat_messages', 'content_expert', schema='stockeasy')
    # ### end Alembic commands ###
