"""add column web link loading count

Revision ID: a817588d0c80
Revises: e14365030a41
Create Date: 2025-05-18 14:26:11.232890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a817588d0c80'
down_revision: Union[str, None] = 'e14365030a41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 공유 채팅 세션 테이블에 조회수 컬럼만 추가
    op.add_column('stockeasy_shared_chat_sessions', sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='세션 조회 횟수'), schema='stockeasy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 공유 채팅 세션 테이블에서 조회수 컬럼만 제거
    op.drop_column('stockeasy_shared_chat_sessions', 'view_count', schema='stockeasy')
    # ### end Alembic commands ###
