"""Remove updated_at column from user_statistics table

Revision ID: c10dab477f4c
Revises: 49a0ef9f1e8e
Create Date: 2025-06-23 02:24:23.991807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c10dab477f4c'
down_revision: Union[str, None] = '49a0ef9f1e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
