"""Add User email in Sesstion table for debug

Revision ID: cec4a2dcda66
Revises: da382b009eb2
Create Date: 2025-02-20 10:55:32.343856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec4a2dcda66'
down_revision: Union[str, None] = 'da382b009eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('sessions', sa.Column('user_email', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'sessions', 'users', ['user_email'], ['email'], ondelete='CASCADE')
    op.drop_constraint('table_histories_user_id_fkey', 'table_histories', type_='foreignkey')
    op.drop_constraint('table_histories_project_id_fkey', 'table_histories', type_='foreignkey')
    op.drop_constraint('table_histories_document_id_fkey', 'table_histories', type_='foreignkey')
    op.create_foreign_key(None, 'table_histories', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'table_histories', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'table_histories', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'table_histories', type_='foreignkey')
    op.drop_constraint(None, 'table_histories', type_='foreignkey')
    op.drop_constraint(None, 'table_histories', type_='foreignkey')
    op.create_foreign_key('table_histories_document_id_fkey', 'table_histories', 'documents', ['document_id'], ['id'])
    op.create_foreign_key('table_histories_project_id_fkey', 'table_histories', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('table_histories_user_id_fkey', 'table_histories', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'user_email')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    # ### end Alembic commands ###
