"""add_cascade_delete_to_chat_history

Revision ID: d11968ec2eb5
Revises: b155fdcd2f47
Create Date: 2025-02-26 21:51:42.264487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11968ec2eb5'
down_revision: Union[str, None] = 'b155fdcd2f47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_history_project_id_fkey', 'chat_history', type_='foreignkey')
    op.create_foreign_key(None, 'chat_history', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.create_foreign_key('chat_history_project_id_fkey', 'chat_history', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
