"""Update models to SQLAlchemy 2.0 and add CASCADE delete

Revision ID: da382b009eb2
Revises: 8617feb03710
Create Date: 2025-02-19 11:50:36.799122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da382b009eb2'
down_revision: Union[str, None] = '8617feb03710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
