"""Add user_statistics table

Revision ID: df8263098851
Revises: 68b2240c89d7
Create Date: 2025-06-22 23:22:00.467445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df8263098851'
down_revision: Union[str, None] = '68b2240c89d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stockeasy_chat_messages', 'content',
               existing_type=sa.TEXT(),
               comment='메시지 텍스트 내용',
               existing_comment='메시지 내용',
               existing_nullable=True,
               schema='stockeasy')
    op.alter_column('stockeasy_chat_messages', 'message_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='메시지 추가 메타데이터 (처리 정보, 컨텍스트 등)',
               existing_comment='메시지 메타데이터 (JSON 형태)',
               existing_nullable=True,
               schema='stockeasy')
    op.drop_index('ix_stockeasy_chat_sessions_stock_code', table_name='stockeasy_chat_sessions', schema='stockeasy')
    op.create_index(op.f('ix_stockeasy_stockeasy_chat_sessions_stock_code'), 'stockeasy_chat_sessions', ['stock_code'], unique=False, schema='stockeasy')
    op.alter_column('web_search_query_cache', 'last_hit_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수정 시간 (Asia/Seoul)',
               existing_comment='최근 hit 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"),
               schema='stockeasy')
    op.drop_index('ix_stockeasy_web_search_query_cache_stock_code', table_name='web_search_query_cache', schema='stockeasy')
    op.drop_index('ix_stockeasy_web_search_result_cache_query_cache_id', table_name='web_search_result_cache', schema='stockeasy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_stockeasy_web_search_result_cache_query_cache_id', 'web_search_result_cache', ['query_cache_id'], unique=False, schema='stockeasy')
    op.create_index('ix_stockeasy_web_search_query_cache_stock_code', 'web_search_query_cache', ['stock_code'], unique=False, schema='stockeasy')
    op.alter_column('web_search_query_cache', 'last_hit_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='최근 hit 시간 (Asia/Seoul)',
               existing_comment='수정 시간 (Asia/Seoul)',
               existing_nullable=False,
               existing_server_default=sa.text("timezone('Asia/Seoul'::text, CURRENT_TIMESTAMP)"),
               schema='stockeasy')
    op.drop_index(op.f('ix_stockeasy_stockeasy_chat_sessions_stock_code'), table_name='stockeasy_chat_sessions', schema='stockeasy')
    op.create_index('ix_stockeasy_chat_sessions_stock_code', 'stockeasy_chat_sessions', ['stock_code'], unique=False, schema='stockeasy')
    op.alter_column('stockeasy_chat_messages', 'message_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='메시지 메타데이터 (JSON 형태)',
               existing_comment='메시지 추가 메타데이터 (처리 정보, 컨텍스트 등)',
               existing_nullable=True,
               schema='stockeasy')
    op.alter_column('stockeasy_chat_messages', 'content',
               existing_type=sa.TEXT(),
               comment='메시지 내용',
               existing_comment='메시지 텍스트 내용',
               existing_nullable=True,
               schema='stockeasy')
    # ### end Alembic commands ###
