"""add share chat tables

Revision ID: e14365030a41
Revises: 77adc861e89f
Create Date: 2025-05-16 03:14:02.473423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e14365030a41'
down_revision: Union[str, None] = '77adc861e89f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockeasy_shared_chat_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='공유 세션 ID'),
    sa.Column('original_session_id', sa.UUID(), nullable=False, comment='원본 채팅 세션 ID'),
    sa.Column('share_uuid', sa.String(length=36), nullable=False, comment='공유 링크용 UUID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='채팅 세션 제목'),
    sa.Column('stock_code', sa.String(length=20), nullable=True, comment='종목 코드'),
    sa.Column('stock_name', sa.String(length=100), nullable=True, comment='종목명'),
    sa.Column('stock_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='종목 관련 추가 정보'),
    sa.Column('agent_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='세션의 에이전트 처리 결과 데이터'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='생성 시간 (Asia/Seoul)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='수정 시간 (Asia/Seoul)'),
    sa.ForeignKeyConstraint(['original_session_id'], ['stockeasy.stockeasy_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='stockeasy'
    )
    op.create_index(op.f('ix_stockeasy_stockeasy_shared_chat_sessions_original_session_id'), 'stockeasy_shared_chat_sessions', ['original_session_id'], unique=False, schema='stockeasy')
    op.create_index(op.f('ix_stockeasy_stockeasy_shared_chat_sessions_share_uuid'), 'stockeasy_shared_chat_sessions', ['share_uuid'], unique=True, schema='stockeasy')
    op.create_index(op.f('ix_stockeasy_stockeasy_shared_chat_sessions_stock_code'), 'stockeasy_shared_chat_sessions', ['stock_code'], unique=False, schema='stockeasy')
    
    op.create_table('stockeasy_shared_chat_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='공유 메시지 ID'),
    sa.Column('chat_session_id', sa.UUID(), nullable=False, comment='공유 채팅 세션 ID'),
    sa.Column('original_message_id', sa.UUID(), nullable=True, comment='원본 메시지 ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='메시지 역할 (user, assistant, system)'),
    sa.Column('stock_code', sa.String(length=20), nullable=True, comment='종목 코드'),
    sa.Column('stock_name', sa.String(length=100), nullable=True, comment='종목명'),
    sa.Column('content_type', sa.String(length=50), server_default='text', nullable=False, comment='메시지 콘텐츠 타입'),
    sa.Column('content', sa.Text(), nullable=True, comment='메시지 텍스트 내용'),
    sa.Column('content_expert', sa.Text(), nullable=True, comment='전문가 메시지 텍스트 내용'),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='구조화된 메시지 컴포넌트 배열'),
    sa.Column('message_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='메시지 타입별 구조화된 데이터'),
    sa.Column('data_url', sa.Text(), nullable=True, comment='외부 리소스 URL'),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='메시지 추가 메타데이터'),
    sa.Column('agent_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='에이전트 처리 결과 데이터'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='생성 시간 (Asia/Seoul)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='수정 시간 (Asia/Seoul)'),
    sa.ForeignKeyConstraint(['chat_session_id'], ['stockeasy.stockeasy_shared_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='stockeasy'
    )
    op.create_index('ix_stockeasy_shared_chat_messages_chat_session_id_created_at', 'stockeasy_shared_chat_messages', ['chat_session_id', 'created_at'], unique=False, schema='stockeasy')
    op.create_index(op.f('ix_stockeasy_stockeasy_shared_chat_messages_chat_session_id'), 'stockeasy_shared_chat_messages', ['chat_session_id'], unique=False, schema='stockeasy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stockeasy_stockeasy_shared_chat_messages_chat_session_id'), table_name='stockeasy_shared_chat_messages', schema='stockeasy')
    op.drop_index('ix_stockeasy_shared_chat_messages_chat_session_id_created_at', table_name='stockeasy_shared_chat_messages', schema='stockeasy')
    op.drop_table('stockeasy_shared_chat_messages', schema='stockeasy')
    op.drop_index(op.f('ix_stockeasy_stockeasy_shared_chat_sessions_stock_code'), table_name='stockeasy_shared_chat_sessions', schema='stockeasy')
    op.drop_index(op.f('ix_stockeasy_stockeasy_shared_chat_sessions_share_uuid'), table_name='stockeasy_shared_chat_sessions', schema='stockeasy')
    op.drop_index(op.f('ix_stockeasy_stockeasy_shared_chat_sessions_original_session_id'), table_name='stockeasy_shared_chat_sessions', schema='stockeasy')
    op.drop_table('stockeasy_shared_chat_sessions', schema='stockeasy')
    # ### end Alembic commands ###
