"""add columns stockeasy_chat_messages, stock_code, stock_name

Revision ID: f4432679b9f6
Revises: 40f14be49bf6
Create Date: 2025-04-05 20:04:00.639305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision: str = 'f4432679b9f6'
down_revision: Union[str, None] = '40f14be49bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 스키마와 테이블 존재 여부 확인을 위한 인스펙터 생성
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    
    # stockeasy_chat_messages 테이블에 칼럼 추가
    # 칼럼이 존재하지 않는 경우에만 추가
    columns = [col['name'] for col in inspector.get_columns('stockeasy_chat_messages', schema='stockeasy')]
    
    if 'stock_code' not in columns:
        op.add_column('stockeasy_chat_messages', 
                     sa.Column('stock_code', sa.String(length=20), nullable=True, comment='종목 코드'),
                     schema='stockeasy')
    
    if 'stock_name' not in columns:
        op.add_column('stockeasy_chat_messages',
                     sa.Column('stock_name', sa.String(length=100), nullable=True, comment='종목명'),
                     schema='stockeasy')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 칼럼 존재 여부 확인 후 삭제
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    columns = [col['name'] for col in inspector.get_columns('stockeasy_chat_messages', schema='stockeasy')]
    
    if 'stock_code' in columns:
        op.drop_column('stockeasy_chat_messages', 'stock_code', schema='stockeasy')
    
    if 'stock_name' in columns:
        op.drop_column('stockeasy_chat_messages', 'stock_name', schema='stockeasy')
    # ### end Alembic commands ###
