"""add columns stockeasy_chat_messages, stock_code, stock_name

Revision ID: f4432679b9f6
Revises: 40f14be49bf6
Create Date: 2025-04-05 20:04:00.639305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision: str = 'f4432679b9f6'
down_revision: Union[str, None] = '40f14be49bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 스키마와 테이블 존재 여부 확인을 위한 인스펙터 생성
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    
    # stockeasy_chat_messages 테이블이 존재하는지 확인
    tables = inspector.get_table_names(schema='stockeasy')
    if 'stockeasy_chat_messages' in tables:
        # stockeasy_chat_messages 테이블에 칼럼 존재 여부 확인
        columns = [col['name'] for col in inspector.get_columns('stockeasy_chat_messages', schema='stockeasy')]
        
        # session_id와 chat_session_id 중 하나만 존재하는지 확인
        if 'session_id' in columns and 'chat_session_id' not in columns:
            # 외래 키 제약 조건 삭제
            op.drop_constraint(
                'stockeasy_chat_messages_session_id_fkey',
                'stockeasy_chat_messages',
                schema='stockeasy',
                type_='foreignkey'
            )
            
            # session_id에서 chat_session_id로 컬럼 이름 변경
            op.alter_column(
                'stockeasy_chat_messages',
                'session_id',
                new_column_name='chat_session_id',
                schema='stockeasy'
            )
            
            # 새 외래 키 제약 조건 추가
            op.create_foreign_key(
                'stockeasy_chat_messages_chat_session_id_fkey',
                'stockeasy_chat_messages',
                'stockeasy_chat_sessions',
                ['chat_session_id'],
                ['id'],
                source_schema='stockeasy',
                referent_schema='stockeasy',
                ondelete='CASCADE'
            )
            
            # 인덱스 재생성
            if op.f('ix_stockeasy_stockeasy_chat_messages_session_id') in [idx['name'] for idx in inspector.get_indexes('stockeasy_chat_messages', schema='stockeasy')]:
                op.drop_index(
                    op.f('ix_stockeasy_stockeasy_chat_messages_session_id'),
                    table_name='stockeasy_chat_messages',
                    schema='stockeasy'
                )
            
            if 'ix_stockeasy_chat_messages_session_id_created_at' in [idx['name'] for idx in inspector.get_indexes('stockeasy_chat_messages', schema='stockeasy')]:
                op.drop_index(
                    'ix_stockeasy_chat_messages_session_id_created_at',
                    table_name='stockeasy_chat_messages',
                    schema='stockeasy'
                )
            
            op.create_index(
                op.f('ix_stockeasy_stockeasy_chat_messages_chat_session_id'),
                'stockeasy_chat_messages',
                ['chat_session_id'],
                unique=False,
                schema='stockeasy'
            )
            
            op.create_index(
                'ix_stockeasy_chat_messages_chat_session_id_created_at',
                'stockeasy_chat_messages',
                ['chat_session_id', 'created_at'],
                unique=False,
                schema='stockeasy'
            )
        
        # stock_code와 stock_name 칼럼 추가
        if 'stock_code' not in columns:
            op.add_column(
                'stockeasy_chat_messages',
                sa.Column('stock_code', sa.String(length=20), nullable=True, comment='종목 코드'),
                schema='stockeasy'
            )
        
        if 'stock_name' not in columns:
            op.add_column(
                'stockeasy_chat_messages',
                sa.Column('stock_name', sa.String(length=100), nullable=True, comment='종목명'),
                schema='stockeasy'
            )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 스키마와 테이블 존재 여부 확인
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names(schema='stockeasy')
    
    if 'stockeasy_chat_messages' in tables:
        # 칼럼 존재 여부 확인
        columns = [col['name'] for col in inspector.get_columns('stockeasy_chat_messages', schema='stockeasy')]
        
        # stock_code와 stock_name 칼럼 삭제
        if 'stock_code' in columns:
            op.drop_column('stockeasy_chat_messages', 'stock_code', schema='stockeasy')
        
        if 'stock_name' in columns:
            op.drop_column('stockeasy_chat_messages', 'stock_name', schema='stockeasy')
        
        # chat_session_id에서 session_id로 롤백
        if 'chat_session_id' in columns and 'session_id' not in columns:
            # 외래 키 제약 조건 삭제
            op.drop_constraint(
                'stockeasy_chat_messages_chat_session_id_fkey',
                'stockeasy_chat_messages',
                schema='stockeasy',
                type_='foreignkey'
            )
            
            # chat_session_id에서 session_id로 컬럼 이름 변경
            op.alter_column(
                'stockeasy_chat_messages',
                'chat_session_id',
                new_column_name='session_id',
                schema='stockeasy'
            )
            
            # 원래 외래 키 제약 조건 추가
            op.create_foreign_key(
                'stockeasy_chat_messages_session_id_fkey',
                'stockeasy_chat_messages',
                'stockeasy_chat_sessions',
                ['session_id'],
                ['id'],
                source_schema='stockeasy',
                referent_schema='stockeasy',
                ondelete='CASCADE'
            )
            
            # 인덱스 재생성
            indices = inspector.get_indexes('stockeasy_chat_messages', schema='stockeasy')
            index_names = [idx['name'] for idx in indices]
            
            if 'ix_stockeasy_stockeasy_chat_messages_chat_session_id' in index_names:
                op.drop_index(
                    op.f('ix_stockeasy_stockeasy_chat_messages_chat_session_id'),
                    table_name='stockeasy_chat_messages',
                    schema='stockeasy'
                )
            
            if 'ix_stockeasy_chat_messages_chat_session_id_created_at' in index_names:
                op.drop_index(
                    'ix_stockeasy_chat_messages_chat_session_id_created_at',
                    table_name='stockeasy_chat_messages',
                    schema='stockeasy'
                )
            
            op.create_index(
                op.f('ix_stockeasy_stockeasy_chat_messages_session_id'),
                'stockeasy_chat_messages',
                ['session_id'],
                unique=False,
                schema='stockeasy'
            )
            
            op.create_index(
                'ix_stockeasy_chat_messages_session_id_created_at',
                'stockeasy_chat_messages',
                ['session_id', 'created_at'],
                unique=False,
                schema='stockeasy'
            )
    # ### end Alembic commands ###
