"""create financial data tables

Revision ID: fdcd55a3281a
Revises: 4a5bc791d38e
Create Date: 2025-04-20 20:40:26.366960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdcd55a3281a'
down_revision: Union[str, None] = '4a5bc791d38e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_code', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('market_type', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='생성 시간 (Asia/Seoul)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='수정 시간 (Asia/Seoul)'),
    sa.PrimaryKeyConstraint('id'),
    schema='stockeasy'
    )
    op.create_index(op.f('ix_stockeasy_companies_company_code'), 'companies', ['company_code'], unique=True, schema='stockeasy')
    op.create_index(op.f('ix_stockeasy_companies_id'), 'companies', ['id'], unique=False, schema='stockeasy')
    op.create_table('financial_item_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('standard_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='생성 시간 (Asia/Seoul)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='수정 시간 (Asia/Seoul)'),
    sa.PrimaryKeyConstraint('id'),
    schema='stockeasy'
    )
    op.create_index(op.f('ix_stockeasy_financial_item_mappings_category'), 'financial_item_mappings', ['category'], unique=False, schema='stockeasy')
    op.create_index(op.f('ix_stockeasy_financial_item_mappings_id'), 'financial_item_mappings', ['id'], unique=False, schema='stockeasy')
    op.create_index(op.f('ix_stockeasy_financial_item_mappings_item_code'), 'financial_item_mappings', ['item_code'], unique=True, schema='stockeasy')
    op.create_table('financial_item_raw_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('raw_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='생성 시간 (Asia/Seoul)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='수정 시간 (Asia/Seoul)'),
    sa.ForeignKeyConstraint(['mapping_id'], ['stockeasy.financial_item_mappings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_name', 'mapping_id', name='uq_raw_name_mapping'),
    schema='stockeasy'
    )
    op.create_index(op.f('ix_stockeasy_financial_item_raw_mappings_id'), 'financial_item_raw_mappings', ['id'], unique=False, schema='stockeasy')
    op.create_index(op.f('ix_stockeasy_financial_item_raw_mappings_raw_name'), 'financial_item_raw_mappings', ['raw_name'], unique=False, schema='stockeasy')
    op.create_table('financial_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('report_quarter', sa.Integer(), nullable=True),
    sa.Column('year_month', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='생성 시간 (Asia/Seoul)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='수정 시간 (Asia/Seoul)'),
    sa.ForeignKeyConstraint(['company_id'], ['stockeasy.companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'report_year', 'report_quarter', name='uq_company_report'),
    schema='stockeasy'
    )
    op.create_index(op.f('ix_stockeasy_financial_reports_id'), 'financial_reports', ['id'], unique=False, schema='stockeasy')
    op.create_index(op.f('ix_stockeasy_financial_reports_year_month'), 'financial_reports', ['year_month'], unique=False, schema='stockeasy')
    op.create_table('summary_financial_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('year_month', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=30, scale=2), nullable=False),
    sa.Column('display_unit', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='생성 시간 (Asia/Seoul)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Seoul', CURRENT_TIMESTAMP)"), nullable=False, comment='수정 시간 (Asia/Seoul)'),
    sa.ForeignKeyConstraint(['company_id'], ['stockeasy.companies.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['stockeasy.financial_item_mappings.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['stockeasy.financial_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'company_id', 'item_id', 'year_month', name='uq_summary_data'),
    schema='stockeasy'
    )
    op.create_index('idx_summary_fin_company_item', 'summary_financial_data', ['company_id', 'item_id'], unique=False, schema='stockeasy', postgresql_using='btree')
    op.create_index('idx_summary_fin_company_item_year_month', 'summary_financial_data', ['company_id', 'item_id', 'year_month'], unique=False, schema='stockeasy', postgresql_using='btree')
    op.create_index('idx_summary_fin_company_year_month', 'summary_financial_data', ['company_id', 'year_month'], unique=False, schema='stockeasy', postgresql_using='btree')
    op.create_index('idx_summary_fin_item_year_month', 'summary_financial_data', ['item_id', 'year_month'], unique=False, schema='stockeasy', postgresql_using='btree')
    op.create_index('idx_summary_fin_year_month', 'summary_financial_data', ['year_month'], unique=False, schema='stockeasy', postgresql_using='btree')
    op.create_index(op.f('ix_stockeasy_summary_financial_data_id'), 'summary_financial_data', ['id'], unique=False, schema='stockeasy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stockeasy_summary_financial_data_id'), table_name='summary_financial_data', schema='stockeasy')
    op.drop_index('idx_summary_fin_year_month', table_name='summary_financial_data', schema='stockeasy', postgresql_using='btree')
    op.drop_index('idx_summary_fin_item_year_month', table_name='summary_financial_data', schema='stockeasy', postgresql_using='btree')
    op.drop_index('idx_summary_fin_company_year_month', table_name='summary_financial_data', schema='stockeasy', postgresql_using='btree')
    op.drop_index('idx_summary_fin_company_item_year_month', table_name='summary_financial_data', schema='stockeasy', postgresql_using='btree')
    op.drop_index('idx_summary_fin_company_item', table_name='summary_financial_data', schema='stockeasy', postgresql_using='btree')
    op.drop_table('summary_financial_data', schema='stockeasy')
    op.drop_index(op.f('ix_stockeasy_financial_reports_year_month'), table_name='financial_reports', schema='stockeasy')
    op.drop_index(op.f('ix_stockeasy_financial_reports_id'), table_name='financial_reports', schema='stockeasy')
    op.drop_table('financial_reports', schema='stockeasy')
    op.drop_index(op.f('ix_stockeasy_financial_item_raw_mappings_raw_name'), table_name='financial_item_raw_mappings', schema='stockeasy')
    op.drop_index(op.f('ix_stockeasy_financial_item_raw_mappings_id'), table_name='financial_item_raw_mappings', schema='stockeasy')
    op.drop_table('financial_item_raw_mappings', schema='stockeasy')
    op.drop_index(op.f('ix_stockeasy_financial_item_mappings_item_code'), table_name='financial_item_mappings', schema='stockeasy')
    op.drop_index(op.f('ix_stockeasy_financial_item_mappings_id'), table_name='financial_item_mappings', schema='stockeasy')
    op.drop_index(op.f('ix_stockeasy_financial_item_mappings_category'), table_name='financial_item_mappings', schema='stockeasy')
    op.drop_table('financial_item_mappings', schema='stockeasy')
    op.drop_index(op.f('ix_stockeasy_companies_id'), table_name='companies', schema='stockeasy')
    op.drop_index(op.f('ix_stockeasy_companies_company_code'), table_name='companies', schema='stockeasy')
    op.drop_table('companies', schema='stockeasy')
    # ### end Alembic commands ###
